### ISSUE TITLE
[Code Quality] Use existing functions to do things

### ISSUE THREAD

**Issue by vjFaLk** [frappe/bench_manager#23]
For example, in the bench repo, there is already a function to update the site config : https://github.com/frappe/bench/blob/master/bench/config/common_site_config.py#L43

And you can use that instead of writing your own function : https://github.com/frappe/bench_manager/blob/develop/bench_manager/bench_manager/doctype/bench_settings/bench_settings.py#L28

**Comment by codingCoffee** [comment]
This function is present in bench and not in frappé. Hence it won't be fixed.

**Comment by vjFaLk** [comment]
You can import functions from bench by doing `from bench import`, but you'll have to install it in the environment. Hm.
